// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brewer-week1/Week1Guide.tsx": () => import("../components/mockups/brewer-week1/Week1Guide.tsx"),
  "./components/mockups/concentrate-aio/CondensedAio.tsx": () => import("../components/mockups/concentrate-aio/CondensedAio.tsx"),
  "./components/mockups/export-card-editor/ExportCardEditor.tsx": () => import("../components/mockups/export-card-editor/ExportCardEditor.tsx"),
  "./components/mockups/ion-ratios/GuidedRatioLocking.tsx": () => import("../components/mockups/ion-ratios/GuidedRatioLocking.tsx"),
  "./components/mockups/ion-ratios/QuickRatioTable.tsx": () => import("../components/mockups/ion-ratios/QuickRatioTable.tsx"),
  "./components/mockups/recipe-mineral-label/RecipeStepsMineralLabel.tsx": () => import("../components/mockups/recipe-mineral-label/RecipeStepsMineralLabel.tsx"),
  "./components/mockups/water-browser/MineralFingerprint.tsx": () => import("../components/mockups/water-browser/MineralFingerprint.tsx"),
  "./components/mockups/water-browser/SortableTable.tsx": () => import("../components/mockups/water-browser/SortableTable.tsx"),
  "./components/mockups/water-tasting-focused/FocusedWaterTasting.tsx": () => import("../components/mockups/water-tasting-focused/FocusedWaterTasting.tsx"),
  "./components/mockups/water-tasting-focused/WaterTastingScoring.tsx": () => import("../components/mockups/water-tasting-focused/WaterTastingScoring.tsx"),
  "./components/mockups/water-tasting-focused/WaterTastingTab.tsx": () => import("../components/mockups/water-tasting-focused/WaterTastingTab.tsx"),
  "./components/mockups/water-tasting/CurrentWaterTasting.tsx": () => import("../components/mockups/water-tasting/CurrentWaterTasting.tsx"),
  "./components/mockups/water-tasting/WaterTastingScoring.tsx": () => import("../components/mockups/water-tasting/WaterTastingScoring.tsx"),
  "./components/mockups/water-tasting/WaterTastingTab.tsx": () => import("../components/mockups/water-tasting/WaterTastingTab.tsx"),
  "./components/mockups/watermancer-readings/Compact.tsx": () => import("../components/mockups/watermancer-readings/Compact.tsx"),
  "./components/mockups/watermancer-readings/Current.tsx": () => import("../components/mockups/watermancer-readings/Current.tsx"),
  "./components/mockups/workframe/WorkframeProfileBuilder.tsx": () => import("../components/mockups/workframe/WorkframeProfileBuilder.tsx")
};
