// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brewer-week1/Week1Guide.tsx": () => import("../components/mockups/brewer-week1/Week1Guide.tsx")
};
